.TH KBDD 1 "OCT 2010" Linux "User Manual" 
.SH NAME kbdd - simple per-window keyboard layout daemon
.SH SYNOPSIS
.B kbdd
.RB [ \-v ]
.SH DESCRIPTION
kbdd is a simple per-window keyboard layout daemon. It can be run via
a shell.
.SH BUGS
if you find any bug please report to http://github.com/qnikst/kbdd/issues
.SH AUTORS
Alexander V. Vershilov 
