.TH KBDD 1 "OCT 2010" Linux "User Manual" 
.SH NAME kbdd - simple per-window keyboard layout daemon
.SH SYNOPSIS
.B kbdd
.RB [ \-v ]
.SH DESCRIPTION
kbdd is a simple per-window keyboard layout daemon. It can be run via
a shell.

kbbd has dbus interface with next methods:

getLayoutName( uint32 ) - returns string presentation of group name
set_layout(uint32 )     - set current group
next_layout             - switch to the next keyboard layout
prev_layout             - switch to the previous keyboard layout

and events(signals):

layoutChanged           - returns new group number
layoutNameChanged       - returns name for the new group 

so you can change encoding with dbus-send command:
   dbus-send dbus-send --dest=ru.gentoo.KbddService /ru/gentoo/KbddService ru.gentoo.kbdd.set_layout uint32:1
To get more information about kbdd usage you can vizit https://github.com/qnikst/kbdd/wiki/Usecases page

.SH BUGS
For some users meta-keys (like alt or Meta4 stick) but there is not enough
report data to investigate if this a kbdd bug or not.
If you find any bug please report to http://github.com/qnikst/kbdd/issues
.SH AUTORS
Alexander V. Vershilov 
