TOPDIR=$(shell pwd)

include $(TOPDIR)/common.mk

FILTER:=src/kbdd.c

FILES:=$(filter-out $(FILTER),$(wildcard src/*.c))
FILES:=$(FILES:.c=.o)
HEADERS:=$(wildcard include/*.h)

SRCDIR=$(TOPDIR)/src

GLIB_LIBS = `pkg-config glib-2.0 --libs`
GLIB_CFLAGS = `pkg-config glib-2.0 --cflags`
GLIB_GENMARSHAL=`pkg-config glib-2.0 --variable=glib_genmarshal`


KBDD_OPT=
KBDD_DEP = src/libkbdd.o

ifdef WITH_DBUS
DBUS_TOOL   =dbus-binding-tool
DBUS_HEADERS=src/server-bindings.h src/client-bindings.h
DBUS_PREFIX =kbdd
DBUS_LIBS   = `pkg-config dbus-glib-1 --libs`
DBUS_CFLAGS = `pkg-config dbus-glib-1 --cflags`

KBDD_LIBS  := ${GLIB_LIBS}
KBDD_FLAGS := ${GLIB_CFLAGS}
KBDD_LIBS  += ${DBUS_LIBS}
KBDD_FLAGS += ${DBUS_CFLAGS}
KBDD_OPT   += -DWITH_DBUS
KBDD_DEP   += dbus2 src/kbdd-service.o
endif

ifeq (${DEBUG},1)
	DEBUGOPT = -DDEBUG
endif

#big rules
all: src/kbdd 

dbus2: src/kbdd-service-glue.h src/kbdd-marshal.c src/kbdd-marshal.h


src/kbdd.c:
src/storage.c:

src/kbdd.xml:

src/kbdd.o: src/kbdd.c 
	$(CC) -DPACKAGE_NAME=\"${PACKAGE_NAME}\" -DPACKAGE_VERSION=\"${PACKAGE_VERSION}\" \
		-DWITH_DBUS \
		${GLIB_LIBS} ${GLIB_CFLAGS} ${DBUS_LIBS} ${DBUS_CFLAGS} -lX11 -c -o $@ $< 

src/storage.o: src/storage.c
	$(CC) $(CFLAGS) ${GLIB_LIBS} ${GLIB_CFLAGS} -DSTORAGE_GHASH -fPIC -c -o $@ $< 

src/libkbdd.o: src/libkbdd.c
	$(CC) $(CFLAGS)  -lX11 -fPIC -c -o $@ $<

src/kbdd: src/kbdd.o src/kbdd-marshal.o src/m-kbdd-service.o src/storage.o src/libkbdd.o
	$(CC) -o src/kbdd src/kbdd.o src/kbdd-marshal.o src/m-kbdd-service.o \
		src/storage.o src/libkbdd.o \
		-lX11 ${DBUS_CFLAGS} ${DBUS_LIBS} ${GLIB_CFLAGS} ${GLIB_LIBS}

options:
	@echo libkbdd build options
	@echo "CFLAGS  = ${CFLAGS}"
	@echo "LDFLAGS = ${LDFLAGS}"
	@echo "CC      = ${CC}"

#src/libkbdd.so: src/libkbdd.o
#	$(CC) $(CFLAGS) -shared libkbdd.o storage.o -o libkbdd.so ${GLIB_LIBS} ${GLIB_CFLAGS} -lX11 -fPIC


install: all
	echo "INSTALL"
	$(INSTALL) -d -m 0755 $(DESTDIR)$(PREFIX)/bin
	$(INSTALL) -d -m 0755 $(DESTDIR)$(PREFIX)/include
	$(INSTALL) -d -m 0755 $(DESTDIR)$(PREFIX)/lib
	$(INSTALL) -m 0755 kbdd $(DESTDIR)$(PREFIX)/bin/
	$(INSTALL) -m 0644 libkbdd.so $(DESTDIR)$(PREFIX)/lib
	$(INSTALL) -m 0644 src/libkbdd.h $(DESTDIR)$(PREFIX)/include
	$(INSTALL) -m 0644 kbdd.1 ${DESTDIR}${MANPREFIX}/man1/kbdd.1
	@echo "installing dbus files"
	$(INSTALL) -d -m 0755 $(DESTDIR)$(DBUSDIR)/services
	$(INSTALL) -m 0644 data/ru.gentoo.kbdd $(DESTDIR)$(DBUSDIR)/services


clean: 
	@echo removing compilation files
	rm -f *.o *.so kbdd
	@echo removing autogenerated dbus headers
	rm src/*.o
